### ISSUE TITLE
主图无法显示

### ISSUE THREAD

**Issue by Kevin0Jung** [xiaweizi/jsoupJianshuDemo#1]
老哥，为什么主图显示不出来啊

而且头像和作者名还有链接都不行，不过我已经找到原因了，大概是简书更新了类名，部分跟以往不一样了，而且我这边图片要改成相对url才能显示。

**Comment by xiaweizi** [comment]
不好意思，不维护了，项目偏老

**Comment by xiaweizi** [comment]
已修复
